version: '3'
services:
  mysql:
    image: docker.io/bitnami/mongodb:latest
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_ROOT_PASSWORD=123456789


volumes:
  mongodb_data:
    driver: local
